#!/usr/bin/env python3
"""Annotated disassembly of Townfall-Win64-Shipping.exe by RVA.

Usage: python annotate.py <start_rva_hex> [length_hex]
- Resolves enclosing function from symbols_sorted.txt (generated by dump_all.exe)
- Annotates call/jmp targets with the nearest symbol name
- Marks rip-relative loads to named RVAs
"""
import bisect
import sys
import pefile
from capstone import Cs, CS_ARCH_X86, CS_MODE_64

EXE = r"E:\SteamLibrary\steamapps\common\Townfall\Townfall\Binaries\Win64\Townfall-Win64-Shipping.exe"
SYMS = r"N:\Projects\Slient_Hill_Townfall_Ultrawide\tools\symbols_sorted.txt"
IMAGE_BASE = 0x140000000


def load_symbols():
    rv, names = [], []
    with open(SYMS, "r", errors="replace") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line:
                continue
            addr, _, name = line.partition("\t")
            try:
                r = int(addr, 16)
            except ValueError:
                continue
            rv.append(r)
            names.append(name)
    return rv, names


def main():
    start = int(sys.argv[1], 16)
    length = int(sys.argv[2], 16) if len(sys.argv) > 2 else 0x800

    sym_rv, sym_names = load_symbols()
    pe = pefile.PE(EXE, fast_load=True)
    data = open(EXE, "rb").read()

    def rva_to_off(addr):
        for s in pe.sections:
            va = s.VirtualAddress
            size = max(s.Misc_VirtualSize, s.SizeOfRawData)
            if va <= addr < va + size:
                return s.PointerToRawData + (addr - va)
        return None

    i = bisect.bisect_right(sym_rv, start) - 1
    if i >= 0:
        print(f"# enclosing symbol: 0x{sym_rv[i]:X} {sym_names[i]}")

    off = rva_to_off(start)
    code = data[off : off + length]
    md = Cs(CS_ARCH_X86, CS_MODE_64)
    for insn in md.disasm(code, start + IMAGE_BASE):
        rva = insn.address - IMAGE_BASE
        note = ""
        if insn.mnemonic == "call" and insn.op_str.startswith("0x"):
            tgt = int(insn.op_str, 16) - IMAGE_BASE
            j = bisect.bisect_right(sym_rv, tgt) - 1
            if j >= 0 and tgt - sym_rv[j] < 0x20000:
                note = f"  ; {sym_names[j]}"
        elif insn.mnemonic in ("lea", "mov", "movss", "movsd", "cmp", "xor", "andps", "comiss", "addss", "mulss", "divss", "subss") and "rip" in insn.op_str:
            import re
            m = re.search(r"0x([0-9a-f]+)", insn.op_str.split("rip")[-1])
            if m:
                tgt = int(m.group(1), 16) - IMAGE_BASE
                j = bisect.bisect_right(sym_rv, tgt) - 1
                if j >= 0 and tgt - sym_rv[j] < 0x40:
                    note = f"  ; -> {sym_names[j]}"
        b = " ".join(f"{x:02X}" for x in insn.bytes)
        print(f"{rva:>10X}  {b:<26} {insn.mnemonic:<8} {insn.op_str}{note}")


if __name__ == "__main__":
    main()
